"""
Epistemic Foraging Module for SAGE

Modifies the Expected Free Energy (G) calculation to heavily prioritize
"Epistemic Value" (Information Gain) over "Pragmatic Value" (Goal Seeking).
This mathematically induces Curiosity in the agent, forcing it to 
test hypotheses where its Confidence (c) is lowest.
"""

from typing import Dict, Any
import math
from sage.logic.nal import NALTruthValue

class EpistemicForager:
    """
    Evaluates the "curiosity" value of a novel hypothesis generated by NARS.
    """
    
    @staticmethod
    def calculate_epistemic_value(hypothesis_truth: NALTruthValue) -> float:
        """
        Calculates the Shannon Entropy / Ambiguity of a specific belief.
        In Active Inference, Epistemic Value is maximized when uncertainty is highest.
        
        A belief with Confidence c=1.0 has 0 epistemic value (we already know it).
        A belief with Confidence c=0.0 has maximum epistemic value (a pure guess).
        """
        uncertainty = 1.0 - hypothesis_truth.c
        
        # We also want to prioritize hypotheses where Frequency is around 0.5
        # (It's a complete coin toss, meaning testing it yields maximum bits of info)
        # Using a parabolic curve centered at 0.5
        variance = 4.0 * hypothesis_truth.f * (1.0 - hypothesis_truth.f) 
        
        epistemic_value = uncertainty * variance
        return epistemic_value

    @staticmethod
    def rank_hypotheses(hypotheses: Dict[str, NALTruthValue]) -> str:
        """
        Given a set of newly generated Inductive/Abductive hypotheses,
        selects the one that mathematically promises the most information gain
        if the agent chooses to test it via Do-Calculus.
        """
        best_hypothesis = None
        max_epistemic_value = -1.0
        
        for name, truth_val in hypotheses.items():
            ev = EpistemicForager.calculate_epistemic_value(truth_val)
            
            if ev > max_epistemic_value:
                 max_epistemic_value = ev
                 best_hypothesis = name
                 
        return best_hypothesis
